### ISSUE TITLE
Separate keypair type from SignatureAlgorithm

### ISSUE THREAD

**Issue by nthuemmel** [est31/rcgen#19]
Right now there is no way to map a deserialized `KeyPair` back to a usable `SignatureAlgorithm` (apart from using `is_compatible()` repeatedly for all known algorithms, and that is bugged, see #18 ).

It would improve usability a lot - and also achieve a proper separation of concerns - by having a separate, exposed enum for the type of `KeyPair`, having variants such as `RSA(bitlen)`, `EC_P256`, `EC_P384` and `Ed25519` and being able to query this type for any given `KeyPair` instance. Library users may then choose an appropriate compatible `SignatureAlgorithm`.

**Comment by est31** [comment]
So I think the main demand here is that you want to get a `SignatureAlgorithm` that is compatible to the given `KeyPair` so that you can pass it to the generation routines. Exposing the enum as you suggest is not really desirable as e.g. `EC_P256` and `EC_P384` share the same enum variant. Further curves shouldn't get further enum variants.

Instead, we should just expose a function on the `KeyPair` that returns a suiting `SignatureAlgorithm`.
