### ISSUE TITLE
Can we lower the MSRV?

### ISSUE THREAD

**Issue by djc** [est31/rcgen#75]
0.9 raised the MSRV to 1.56 by virtue of setting the edition to 2021. IMO it would be nice to avoid that for a while longer; for Quinn, for example, we have a policy of sticking to 6-month old versions for the MSRV.

**Comment by est31** [comment]
The MSRV policy of this crate is "whatever latest rust version is". I've written that back when I expected many updates from ring, as they had the same policy. Since then, there have barely been updates though, so I doubt that ring is going to be a problem in the future.

I've used the 2021 edition because I thought that it was 2 releases ago already. But we can wait even more with it.

We can go to edition 2018, which I'd hoped to skip, but given the main changes were to accomodate for the 2015 -> 2018 migration, it makes sense to stay on 2018 at least for a while until 2021 can be adopted.

PRs welcome to add an explicit MSRV. Please with CI enforcement if that's possible :).
